### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by hosseinab** [MfaXyz/Crypto-Triangular-Arbitrage-Bot#3]
hi
thanks for this source
when run this project get error :
Traceback (most recent call last):
  File "C:\Users\Hossein\PycharmProjects\arbitrage2\triarb_kucoin.py", line 20, in <module>
    "USDT": float(user.get_account('account_id')['available']),
  File "C:\Users\Hossein\PycharmProjects\arbitrage2\venv\lib\site-packages\kucoin\user\user.py", line 130, in get_account
    return self._request('GET', '/api/v1/accounts/{accountId}'.format(accountId=accountId))
  File "C:\Users\Hossein\PycharmProjects\arbitrage2\venv\lib\site-packages\kucoin\base_request\base_request.py", line 99, in _request
    return self.check_response_data(response_data)
  File "C:\Users\Hossein\PycharmProjects\arbitrage2\venv\lib\site-packages\kucoin\base_request\base_request.py", line 116, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 200-{"code":"230008","msg":"account not exist"}

**Comment by MfaXyz** [comment]
Hello [hosseinab](https://github.com/hosseinab),
It's because you don't write your account id instead of account_id.
you must get account list and then set your USDT account_id.

for example:
"USDT": float(user.get_account('sqdogh219830eg921oik1ib120')['available']),

**Comment by hosseinab** [comment]
Where can I get account id?
