### ISSUE TITLE
local variable 'pair_a_ask' referenced before assignment

### ISSUE THREAD

**Issue by hosseinab** [MfaXyz/Crypto-Triangular-Arbitrage-Bot#9]
hi . i run this project and get this error :

Traceback (most recent call last):
  File "C:\Users\Hosein\PycharmProjects\Crypto-Triangular-Arbitrage-Bot\triarb_kucoin.py", line 661, in <module>
    third_step()
  File "C:\Users\Hosein\PycharmProjects\Crypto-Triangular-Arbitrage-Bot\triarb_kucoin.py", line 572, in third_step
    prices_dict = get_price_for_t_pair(t_pair, prices_json)
  File "C:\Users\Hosein\PycharmProjects\Crypto-Triangular-Arbitrage-Bot\triarb_kucoin.py", line 126, in get_price_for_t_pair
    "pair_a_ask": pair_a_ask,
UnboundLocalError: local variable 'pair_a_ask' referenced before assignment

**Comment by MfaXyz** [comment]
Hello @hosseinab,
did you download it and put with triarb_kucoin.py on the same folder? :
![image](https://user-images.githubusercontent.com/76481805/193975576-2ab0f417-f366-47cc-9068-e28d1e63989b.png)

**Comment by MfaXyz** [comment]
@hosseinab, so maybe you should run first_step() and second_step() to create new json!

**Comment by hosseinab** [comment]
@MfaXyz 
thank you for answer . this problem fixed .
i get another error :

``` 
{'profit_loss': 0.0036818770215720775, 'real_rate_perc': 0.0248817957743147, 'swap_1': 'BTC', 'contract_1': 'BTC-USDT', 'bid_con_1': '20127', 'swap_2': 'USDT', 'contract_2': 'SOLVE-USDT', 'ask_con_2': '0.03506', 'swap_3': 'SOLVE', 'contract_3': 'SOLVE-BTC', 'bid_con_3': '0.000001735', 'contract_1_direction': 'base_to_quote', 'contract_2_direction': 'quote_to_base', 'contract_3_direction': 'base_to_quote'}
BTC-USDT
{'first_amount1': 14.79747304, 'base_increment1': 8, 'available_amount1': '14.79747304', 'final_amount1': '14.64949831'}
Traceback (most recent call last):
  File "C:\Users\Hosein\PycharmProjects\Crypto-Triangular-Arbitrage-Bot\triarb_kucoin.py", line 667, in <module>
    third_step()
  File "C:\Users\Hosein\PycharmProjects\Crypto-Triangular-Arbitrage-Bot\triarb_kucoin.py", line 604, in third_step
    buy = client.create_market_order(real_rate_arb['contract_1'],
  File "C:\Users\Hosein\AppData\Local\Programs\Python\Python310\lib\site-packages\kucoin\trade\trade.py", line 164, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "C:\Users\Hosein\AppData\Local\Programs\Python\Python310\lib\site-packages\kucoin\base_request\base_request.py", line 99, in _request
    return self.check_response_data(response_data)
  File "C:\Users\Hosein\AppData\Local\Programs\Python\Python310\lib\site-packages\kucoin\base_request\base_request.py", line 116, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 200-{"code":"200004","msg":"Balance insufficient!"}


```

**Comment by MfaXyz** [comment]
@hosseinab, so I think you should have BTC to trade!

**Comment by hosseinab** [comment]
@MfaXyz Base Currency in this bot is BTC ?

**Comment by hosseinab** [comment]
@MfaXyz  ok . thank you .
Can I set the base currency on the usdt?

**Comment by MfaXyz** [comment]
> @MfaXyz  ok . thank you .
> Can I set the base currency on the usdt?

Yes.

**Comment by hosseinab** [comment]
@MfaXyz How is it done?

**Comment by MfaXyz** [comment]
> @MfaXyz How is it done?

you should review code.
